<?php 

namespace App\Repositories;

use GuzzleHttp\Client;

class Countries extends GuzzleHttpRequest {

	protected $countries = [
    	["id" => 1,"code" => "AF","title" => "Afghanistan"],
    	["id" => 2,"code" => "AX","title" => "Aland Islands"],
    	["id" => 3,"code" => "AL","title" => "Albania"],
    	["id" => 4,"code" => "DZ","title" => "Algeria"],
    	["id" => 5,"code" => "AS","title" => "American Samoa"],
    	["id" => 6,"code" => "AD","title" => "Andorra"],
    	["id" => 7,"code" => "AO","title" => "Angola"],
    	["id" => 8,"code" => "AI","title" => "Anguilla"],
    	["id" => 9,"code" => "AQ","title" => "Antarctica"],
    	["id" => 10,"code" => "AG","title" => "Antigua And Barbuda"],
    	["id" => 11,"code" => "AR","title" => "Argentina"],
    	["id" => 12,"code" => "AM","title" => "Armenia"],
    	["id" => 13,"code" => "AW","title" => "Aruba"],
    	["id" => 14,"code" => "AU","title" => "Australia"],
    	["id" => 15,"code" => "AT","title" => "Austria"],
    	["id" => 16,"code" => "AZ","title" => "Azerbaijan"],
    	["id" => 17,"code" => "BS","title" => "Bahamas"],
    	["id" => 18,"code" => "BH","title" => "Bahrain"],
    	["id" => 19,"code" => "BD","title" => "Bangladesh"],
    	["id" => 20,"code" => "BB","title" => "Barbados"],
    	["id" => 21,"code" => "BY","title" => "Belarus"],
    	["id" => 22,"code" => "BE","title" => "Belgium"],
    	["id" => 23,"code" => "BZ","title" => "Belize"],
    	["id" => 24,"code" => "BJ","title" => "Benin"],
    	["id" => 25,"code" => "BM","title" => "Bermuda"],
    	["id" => 26,"code" => "BT","title" => "Bhutan"],
    	["id" => 27,"code" => "BO","title" => "Bolivia"],
    	["id" => 28,"code" => "BA","title" => "Bosnia And Herzegovina"],
    	["id" => 29,"code" => "BW","title" => "Botswana"],
    	["id" => 30,"code" => "BV","title" => "Bouvet Island"],
    	["id" => 31,"code" => "BR","title" => "Brazil"],
    	["id" => 32,"code" => "IO","title" => "British Indian Ocean Territory"],
    	["id" => 33,"code" => "BN","title" => "Brunei Darussalam"],
    	["id" => 34,"code" => "BG","title" => "Bulgaria"],
    	["id" => 35,"code" => "BF","title" => "Burkina Faso"],
    	["id" => 36,"code" => "BI","title" => "Burundi"],
    	["id" => 37,"code" => "KH","title" => "Cambodia"],
    	["id" => 38,"code" => "CM","title" => "Cameroon"],
    	["id" => 39,"code" => "CA","title" => "Canada"],
    	["id" => 40,"code" => "CV","title" => "Cape Verde"],
    	["id" => 41,"code" => "KY","title" => "Cayman Islands"],
    	["id" => 42,"code" => "CF","title" => "Central African Republic"],
    	["id" => 43,"code" => "TD","title" => "Chad"],
    	["id" => 44,"code" => "CL","title" => "Chile"],
    	["id" => 45,"code" => "CN","title" => "China"],
    	["id" => 46,"code" => "CX","title" => "Christmas Island"],
    	["id" => 47,"code" => "CC","title" => "Cocos (Keeling) Islands"],
    	["id" => 48,"code" => "CO","title" => "Colombia"],
    	["id" => 49,"code" => "KM","title" => "Comoros"],
    	["id" => 50,"code" => "CG","title" => "Congo"],
    	["id" => 51,"code" => "CD","title" => "Congo, Democratic Republic"],
    	["id" => 52,"code" => "CK","title" => "Cook Islands"],
    	["id" => 53,"code" => "CR","title" => "Costa Rica"],
    	["id" => 54,"code" => "CI","title" => "Cote D'Ivoire"],
    	["id" => 55,"code" => "HR","title" => "Croatia"],
    	["id" => 56,"code" => "CU","title" => "Cuba"],
    	["id" => 57,"code" => "CY","title" => "Cyprus"],
    	["id" => 58,"code" => "CZ","title" => "Czech Republic"],
    	["id" => 59,"code" => "DK","title" => "Denmark"],
    	["id" => 60,"code" => "DJ","title" => "Djibouti"],
    	["id" => 61,"code" => "DM","title" => "Dominica"],
    	["id" => 62,"code" => "DO","title" => "Dominican Republic"],
    	["id" => 63,"code" => "EC","title" => "Ecuador"],
    	["id" => 64,"code" => "EG","title" => "Egypt"],
    	["id" => 65,"code" => "SV","title" => "El Salvador"],
    	["id" => 66,"code" => "GQ","title" => "Equatorial Guinea"],
    	["id" => 67,"code" => "ER","title" => "Eritrea"],
    	["id" => 68,"code" => "EE","title" => "Estonia"],
    	["id" => 69,"code" => "ET","title" => "Ethiopia"],
    	["id" => 70,"code" => "FK","title" => "Falkland Islands (Malvinas)"],
    	["id" => 71,"code" => "FO","title" => "Faroe Islands"],
    	["id" => 72,"code" => "FJ","title" => "Fiji"],
    	["id" => 73,"code" => "FI","title" => "Finland"],
    	["id" => 74,"code" => "FR","title" => "France"],
    	["id" => 75,"code" => "GF","title" => "French Guiana"],
    	["id" => 76,"code" => "PF","title" => "French Polynesia"],
    	["id" => 77,"code" => "TF","title" => "French Southern Territories"],
    	["id" => 78,"code" => "GA","title" => "Gabon"],
    	["id" => 79,"code" => "GM","title" => "Gambia"],
    	["id" => 80,"code" => "GE","title" => "Georgia"],
    	["id" => 81,"code" => "DE","title" => "Germany"],
    	["id" => 82,"code" => "GH","title" => "Ghana"],
    	["id" => 83,"code" => "GI","title" => "Gibraltar"],
    	["id" => 84,"code" => "GR","title" => "Greece"],
    	["id" => 85,"code" => "GL","title" => "Greenland"],
    	["id" => 86,"code" => "GD","title" => "Grenada"],
    	["id" => 87,"code" => "GP","title" => "Guadeloupe"],
    	["id" => 88,"code" => "GU","title" => "Guam"],
    	["id" => 89,"code" => "GT","title" => "Guatemala"],
    	["id" => 90,"code" => "GG","title" => "Guernsey"],
    	["id" => 91,"code" => "GN","title" => "Guinea"],
    	["id" => 92,"code" => "GW","title" => "Guinea-Bissau"],
    	["id" => 93,"code" => "GY","title" => "Guyana"],
    	["id" => 94,"code" => "HT","title" => "Haiti"],
    	["id" => 95,"code" => "HM","title" => "Heard Island & Mcdonald Islands"],
    	["id" => 96,"code" => "VA","title" => "Holy See (Vatican City State)"],
    	["id" => 97,"code" => "HN","title" => "Honduras"],
    	["id" => 98,"code" => "HK","title" => "Hong Kong"],
    	["id" => 99,"code" => "HU","title" => "Hungary"],
    	["id" => 100,"code" => "IS","title" => "Iceland"],
    	["id" => 101,"code" => "IN","title" => "India"],
    	["id" => 102,"code" => "ID","title" => "Indonesia"],
    	["id" => 103,"code" => "IR","title" => "Iran, Islamic Republic Of"],
    	["id" => 104,"code" => "IQ","title" => "Iraq"],
    	["id" => 105,"code" => "IE","title" => "Ireland"],
    	["id" => 106,"code" => "IM","title" => "Isle Of Man"],
    	["id" => 107,"code" => "IL","title" => "Israel"],
    	["id" => 108,"code" => "IT","title" => "Italy"],
    	["id" => 109,"code" => "JM","title" => "Jamaica"],
    	["id" => 110,"code" => "JP","title" => "Japan"],
    	["id" => 111,"code" => "JE","title" => "Jersey"],
    	["id" => 112,"code" => "JO","title" => "Jordan"],
    	["id" => 113,"code" => "KZ","title" => "Kazakhstan"],
    	["id" => 114,"code" => "KE","title" => "Kenya"],
    	["id" => 115,"code" => "KI","title" => "Kiribati"],
    	["id" => 116,"code" => "KR","title" => "Korea"],
    	["id" => 117,"code" => "KW","title" => "Kuwait"],
    	["id" => 118,"code" => "KG","title" => "Kyrgyzstan"],
    	["id" => 119,"code" => "LA","title" => "Lao People's Democratic Republic"],
    	["id" => 120,"code" => "LV","title" => "Latvia"],
    	["id" => 121,"code" => "LB","title" => "Lebanon"],
    	["id" => 122,"code" => "LS","title" => "Lesotho"],
    	["id" => 123,"code" => "LR","title" => "Liberia"],
    	["id" => 124,"code" => "LY","title" => "Libyan Arab Jamahiriya"],
    	["id" => 125,"code" => "LI","title" => "Liechtenstein"],
    	["id" => 126,"code" => "LT","title" => "Lithuania"],
    	["id" => 127,"code" => "LU","title" => "Luxembourg"],
    	["id" => 128,"code" => "MO","title" => "Macao"],
    	["id" => 129,"code" => "MK","title" => "Macedonia"],
    	["id" => 130,"code" => "MG","title" => "Madagascar"],
    	["id" => 131,"code" => "MW","title" => "Malawi"],
    	["id" => 132,"code" => "MY","title" => "Malaysia"],
    	["id" => 133,"code" => "MV","title" => "Maldives"],
    	["id" => 134,"code" => "ML","title" => "Mali"],
    	["id" => 135,"code" => "MT","title" => "Malta"],
    	["id" => 136,"code" => "MH","title" => "Marshall Islands"],
    	["id" => 137,"code" => "MQ","title" => "Martinique"],
    	["id" => 138,"code" => "MR","title" => "Mauritania"],
    	["id" => 139,"code" => "MU","title" => "Mauritius"],
    	["id" => 140,"code" => "YT","title" => "Mayotte"],
    	["id" => 141,"code" => "MX","title" => "Mexico"],
    	["id" => 142,"code" => "FM","title" => "Micronesia, Federated States Of"],
    	["id" => 143,"code" => "MD","title" => "Moldova"],
    	["id" => 144,"code" => "MC","title" => "Monaco"],
    	["id" => 145,"code" => "MN","title" => "Mongolia"],
    	["id" => 146,"code" => "ME","title" => "Montenegro"],
    	["id" => 147,"code" => "MS","title" => "Montserrat"],
    	["id" => 148,"code" => "MA","title" => "Morocco"],
    	["id" => 149,"code" => "MZ","title" => "Mozambique"],
    	["id" => 150,"code" => "MM","title" => "Myanmar"],
    	["id" => 151,"code" => "NA","title" => "Namibia"],
    	["id" => 152,"code" => "NR","title" => "Nauru"],
    	["id" => 153,"code" => "NP","title" => "Nepal"],
    	["id" => 154,"code" => "NL","title" => "Netherlands"],
    	["id" => 155,"code" => "AN","title" => "Netherlands Antilles"],
    	["id" => 156,"code" => "NC","title" => "New Caledonia"],
    	["id" => 157,"code" => "NZ","title" => "New Zealand"],
    	["id" => 158,"code" => "NI","title" => "Nicaragua"],
    	["id" => 159,"code" => "NE","title" => "Niger"],
    	["id" => 160,"code" => "NG","title" => "Nigeria"],
    	["id" => 161,"code" => "NU","title" => "Niue"],
    	["id" => 162,"code" => "NF","title" => "Norfolk Island"],
    	["id" => 163,"code" => "MP","title" => "Northern Mariana Islands"],
    	["id" => 164,"code" => "NO","title" => "Norway"],
    	["id" => 165,"code" => "OM","title" => "Oman"],
    	["id" => 166,"code" => "PK","title" => "Pakistan"],
    	["id" => 167,"code" => "PW","title" => "Palau"],
    	["id" => 168,"code" => "PS","title" => "Palestinian Territory, Occupied"],
    	["id" => 169,"code" => "PA","title" => "Panama"],
    	["id" => 170,"code" => "PG","title" => "Papua New Guinea"],
    	["id" => 171,"code" => "PY","title" => "Paraguay"],
    	["id" => 172,"code" => "PE","title" => "Peru"],
    	["id" => 173,"code" => "PH","title" => "Philippines"],
    	["id" => 174,"code" => "PN","title" => "Pitcairn"],
    	["id" => 175,"code" => "PL","title" => "Poland"],
    	["id" => 176,"code" => "PT","title" => "Portugal"],
    	["id" => 177,"code" => "PR","title" => "Puerto Rico"],
    	["id" => 178,"code" => "QA","title" => "Qatar"],
    	["id" => 179,"code" => "RE","title" => "Reunion"],
    	["id" => 180,"code" => "RO","title" => "Romania"],
    	["id" => 181,"code" => "RU","title" => "Russian Federation"],
    	["id" => 182,"code" => "RW","title" => "Rwanda"],
    	["id" => 183,"code" => "BL","title" => "Saint Barthelemy"],
    	["id" => 184,"code" => "SH","title" => "Saint Helena"],
    	["id" => 185,"code" => "KN","title" => "Saint Kitts And Nevis"],
    	["id" => 186,"code" => "LC","title" => "Saint Lucia"],
    	["id" => 187,"code" => "MF","title" => "Saint Martin"],
    	["id" => 188,"code" => "PM","title" => "Saint Pierre And Miquelon"],
    	["id" => 189,"code" => "VC","title" => "Saint Vincent And Grenadines"],
    	["id" => 190,"code" => "WS","title" => "Samoa"],
    	["id" => 191,"code" => "SM","title" => "San Marino"],
    	["id" => 192,"code" => "ST","title" => "Sao Tome And Principe"],
    	["id" => 193,"code" => "SA","title" => "Saudi Arabia"],
    	["id" => 194,"code" => "SN","title" => "Senegal"],
    	["id" => 195,"code" => "RS","title" => "Serbia"],
    	["id" => 196,"code" => "SC","title" => "Seychelles"],
    	["id" => 197,"code" => "SL","title" => "Sierra Leone"],
    	["id" => 198,"code" => "SG","title" => "Singapore"],
    	["id" => 199,"code" => "SK","title" => "Slovakia"],
    	["id" => 200,"code" => "SI","title" => "Slovenia"],
    	["id" => 201,"code" => "SB","title" => "Solomon Islands"],
    	["id" => 202,"code" => "SO","title" => "Somalia"],
    	["id" => 203,"code" => "ZA","title" => "South Africa"],
    	["id" => 204,"code" => "GS","title" => "South Georgia And Sandwich Isl."],
    	["id" => 205,"code" => "ES","title" => "Spain"],
    	["id" => 206,"code" => "LK","title" => "Sri Lanka"],
    	["id" => 207,"code" => "SD","title" => "Sudan"],
    	["id" => 208,"code" => "SR","title" => "Suriname"],
    	["id" => 209,"code" => "SJ","title" => "Svalbard And Jan Mayen"],
    	["id" => 210,"code" => "SZ","title" => "Swaziland"],
    	["id" => 211,"code" => "SE","title" => "Sweden"],
    	["id" => 212,"code" => "CH","title" => "Switzerland"],
    	["id" => 213,"code" => "SY","title" => "Syrian Arab Republic"],
    	["id" => 214,"code" => "TW","title" => "Taiwan"],
    	["id" => 215,"code" => "TJ","title" => "Tajikistan"],
    	["id" => 216,"code" => "TZ","title" => "Tanzania"],
    	["id" => 217,"code" => "TH","title" => "Thailand"],
    	["id" => 218,"code" => "TL","title" => "Timor-Leste"],
    	["id" => 219,"code" => "TG","title" => "Togo"],
    	["id" => 220,"code" => "TK","title" => "Tokelau"],
    	["id" => 221,"code" => "TO","title" => "Tonga"],
    	["id" => 222,"code" => "TT","title" => "Trinidad And Tobago"],
    	["id" => 223,"code" => "TN","title" => "Tunisia"],
    	["id" => 224,"code" => "TR","title" => "Turkey"],
    	["id" => 225,"code" => "TM","title" => "Turkmenistan"],
    	["id" => 226,"code" => "TC","title" => "Turks And Caicos Islands"],
    	["id" => 227,"code" => "TV","title" => "Tuvalu"],
    	["id" => 228,"code" => "UG","title" => "Uganda"],
    	["id" => 229,"code" => "UA","title" => "Ukraine"],
    	["id" => 230,"code" => "AE","title" => "United Arab Emirates"],
    	["id" => 231,"code" => "GB","title" => "United Kingdom"],
    	["id" => 232,"code" => "US","title" => "United States"],
    	["id" => 233,"code" => "UM","title" => "United States Outlying Islands"],
    	["id" => 234,"code" => "UY","title" => "Uruguay"],
    	["id" => 235,"code" => "UZ","title" => "Uzbekistan"],
    	["id" => 236,"code" => "VU","title" => "Vanuatu"],
    	["id" => 237,"code" => "VE","title" => "Venezuela"],
    	["id" => 238,"code" => "VN","title" => "Viet Nam"],
    	["id" => 239,"code" => "VG","title" => "Virgin Islands, British"],
    	["id" => 240,"code" => "VI","title" => "Virgin Islands, U.S."],
    	["id" => 241,"code" => "WF","title" => "Wallis And Futuna"],
    	["id" => 242,"code" => "EH","title" => "Western Sahara"],
    	["id" => 243,"code" => "YE","title" => "Yemen"],
    	["id" => 244,"code" => "ZM","title" => "Zambia"],
    	["id" => 245,"code" => "ZW","title" => "Zimbabwe"]
    ];

	public function all() {

		return $this->countries;

	}

}